#!/bin/sh -e

if [ -d 'venv' ] ; then
  if [ $OSTYPE == "msys" ] || [ $OSTYPE == "cygwin" ]; then
    export PREFIX="venv/Scripts/"
  else
    export PREFIX="venv/bin/"
  fi
else
  PREFIX=""
fi

set -x

${PREFIX}python setup.py sdist bdist_wheel
${PREFIX}twine check dist/*
${PREFIX}mkdocs build
