#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
export ALL_FILES="starlette tests"
export SOURCE_FILES="starlette"
export TESTS_FILES="tests"

set -x

./scripts/sync-version
${PREFIX}black --check --diff $ALL_FILES
${PREFIX}mypy $SOURCE_FILES
${PREFIX}mypy $TESTS_FILES --disable-error-code no-untyped-def --disable-error-code no-untyped-call
${PREFIX}ruff check $ALL_FILES
