#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
  if [ $OSTYPE == "msys" ] || [ $OSTYPE == "cygwin" ]; then
    export PREFIX="venv/Scripts/"
  else
    export PREFIX="venv/bin/"
  fi
fi

set -x

${PREFIX}coverage report --show-missing --skip-covered --fail-under=100
