#!/bin/sh -e

DEFAULT=""
if [ command -v "python3" ]; then
  DEFAULT="python3"
else
  DEFAULT="python"
fi

# Use the Python executable provided from the `-p` option, or a default.
[ "$1" = "-p" ] && PYTHON=$2 || PYTHON=$DEFAULT

REQUIREMENTS="requirements.txt"
VENV="venv"

set -x

if [ -z "$GITHUB_ACTIONS" ]; then
  "$PYTHON" -m venv "$VENV"
  if [ $OSTYPE == "msys" ] || [ $OSTYPE == "cygwin" ]; then
    PIP="$VENV/Scripts/pip"
  else
    PIP="$VENV/bin/pip"
  fi
else
  PIP="pip"
fi

"$PIP" install -r "$REQUIREMENTS"
"$PIP" install -e .
