#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
  if [ $OSTYPE == "msys" ] || [ $OSTYPE == "cygwin" ]; then
    export PREFIX="venv/Scripts/"
  else
    export PREFIX="venv/bin/"
  fi
fi
export SOURCE_FILES="starlette tests"

set -x

${PREFIX}autoflake --in-place --recursive $SOURCE_FILES
${PREFIX}isort --project=starlette $SOURCE_FILES
${PREFIX}black $SOURCE_FILES
