#!/bin/sh -e

export PREFIX=""
export VENV_DIR=""

if [ -d 'venv' ] ; then
    export VENV_DIR='venv'
elif [ -d '.venv' ] ; then
    export VENV_DIR='.venv'
fi

if [ -n "$VENV_DIR" ] ; then
    export PREFIX="${VENV_DIR}/bin/"
fi

set -x

PYTHONPATH=. ${PREFIX}pytest --ignore ${VENV_DIR} --cov=starlette --cov=tests --cov-fail-under=100 --cov-report=term-missing ${@}
